query QMedium($id: ID!) {
    medium(id: $id) {
        dateCreated
        dateModified
        dateTaken
        id
        filenameDisk
        filenameDownload
        title
        description
        lat
        lng
        status
        mimetype
        favoredBy {
            id
        }
        owner {
            id
        }
        uploader {
            id
        }
        meta {
            ...on ImageMeta {
                width
                height
                cameraMake
                cameraModel
                flash
                fNumber
                iso
            }
            ...on VideoMeta {
                width
                height
                duration
            }
        }
    }
}
