mutation MRotate($id: ID!) {
    rotate(id: $id) {
        dateCreated
        dateModified
        dateTaken
        id
        filenameDisk
        filenameDownload
        title
        description
        location
        status
        mimetype
        country
        region
        place
        address
        favoredBy {
            id
        }
        owner {
            id
        }
        uploader {
            id
        }
        meta {
            ...on ImageMeta {
                width
                height
                cameraMake
                cameraModel
                flash
                fNumber
                iso
                focalLength
            }
            ...on VideoMeta {
                width
                height
                duration
            }
        }
    }
}
