yarnPath: .yarn/releases/yarn-3.2.2.cjs
packageExtensions:
    graphql-config@*:
        peerDependenciesMeta:
            "@types/node":
                optional: true
            typescript:
                optional: true
    ts-node-dev@*:
        peerDependenciesMeta:
            "@types/node":
                optional: true
    "@types/react-datepicker@*":
        peerDependenciesMeta:
            react:
                optional: true
            react-dom:
                optional: true
