version: '3.9'

networks:
    proxy:
        ipam:
            driver: default
            config:
                - subnet: 10.5.0.0/16

services:
    api:
        container_name: api_c
        restart: unless-stopped
        links:
            - web
        build:
            context: .
            target: api
        entrypoint: ['node', 'api/dist']
        depends_on:
            - db
        environment:
            PORT: 11011
        ports:
            - '11011:11011'
        expose:
            - 11011
    web:
        container_name: web_c
        restart: unless-stopped
        build:
            context: .
            target: web
        environment:
            PORT: 3030
        entrypoint: ['node', 'web/server.js']
        ports:
            - '3030:3030'
        expose:
            - 3030
    db:
        container_name: db_c
        image: postgis/postgis:15-3.3-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=stefanbaumeler
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=photos
        ports:
            - '5555:5432'
        expose:
            - 5555
    queue:
        container_name: queue_c
        image: redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        expose:
            - 6379
    mailhog:
        container_name: mailhog_c
        image: mailhog/mailhog
        restart: unless-stopped
        ports:
            - '1025:1025'
            - '8025:8025'
        expose:
            - 1025
            - 8025
        volumes:
            - ./mailhog.auth:/mailhog.auth:ro
    translate:
        container_name: translate_c
        image: libretranslate/libretranslate:latest
        restart: unless-stopped
        ports:
            - '11012:11012'
        expose:
            - 11012
        entrypoint: ['./venv/bin/libretranslate', '--host', '0.0.0.0', '--port', '11012']
    test:
        container_name: test_c
        build:
            context: .
            target: test
        entrypoint: ['yarn', 'seed-and-test']
