version: '3.9'

networks:
    proxy:
        ipam:
            driver: default
            config:
                - subnet: 10.5.0.0/16

volumes:
    search-data:
        driver: local

services:
    api:
        container_name: api_c
        restart: unless-stopped
        links:
            - web
        build:
            context: .
            target: api
        entrypoint: ['node', 'api/dist']
        depends_on:
            - db
            - search
        environment:
            PORT: 11011
        ports:
            - '11011:11011'
        expose:
            - 11011
    web:
        container_name: web_c
        restart: unless-stopped
        build:
            context: .
            target: web
        environment:
            PORT: 3030
        entrypoint: ['node', 'web/server.js']
        ports:
            - '3030:3030'
        expose:
            - 3030
    db:
        container_name: db_c
        image: postgis/postgis:15-3.3-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=stefanbaumeler
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=photos
        ports:
            - '5555:5432'
        expose:
            - 5555
    search:
        container_name: search_c
        image: typesense/typesense:0.23.1
        restart: unless-stopped
        entrypoint: sh -c '/opt/typesense-server --data-dir /data --api-key=asdf --enable-cors'
        ports:
            - '8108:8108'
        volumes:
            - search-data:/data
        healthcheck:
            test: ['CMD-SHELL', 'apt-get update && apt-get install -y curl && curl -f http://localhost:8108/health']
            interval: 10s
            timeout: 5s
            retries: 20
    translate:
        container_name: translate_c
        image: libretranslate/libretranslate:latest
        restart: unless-stopped
        ports:
            - '11012:11012'
        expose:
            - 11012
        entrypoint: ['./venv/bin/libretranslate', '--host', '0.0.0.0', '--port', '11012']
    test:
        container_name: test_c
        build:
            context: .
            target: test
        depends_on:
            search:
                condition: service_healthy
        entrypoint: ['yarn', 'seed-and-test']
