fragment FCover on FlatMedium {
    id
    mimetype
    filenameDisk
    meta {
        ... on ImageMeta {
            width
            height
        }
        ... on VideoMeta {
            width
            height
        }
    }
}
