fragment FMedia on Medium {
    dateCreated
    dateModified
    dateTaken
    id
    filenameDisk
    filenameDownload
    title
    description
    location
    country
    region
    place
    address
    status
    mimetype
    favoredBy {
        id
    }
    owner {
        id
        firstName
        lastName
    }
    uploader {
        id
        firstName
        lastName
    }
    meta {
        ...on ImageMeta {
            width
            height
            cameraMake
            cameraModel
            flash
            fNumber
            iso
        }
        ...on VideoMeta {
            width
            height
            duration
        }
    }
}
