query MediaQuery {
    media {
        date_created
        date_modified
        date_taken
        id
        filename_disk
        filename_download
        title
        description
        width
        height
        camera_make
        camera_model
        flash
        f_number
        iso
        lat
        lng
    }
}
