query MediaQuery($status: String) {
    media(status: $status) {
        dateCreated
        dateModified
        dateTaken
        id
        filenameDisk
        filenameDownload
        title
        description
        width
        height
        cameraMake
        cameraModel
        flash
        fNumber
        iso
        lat
        lng
        status
    }
}
