query QAlbums {
    albums {
        id
        title
        description
        cover {
            ...FMedia
        }
        owner {
            id
            firstName
            lastName
        },
        albumMedia {
            idMedium
        }
    }
}
