query QAlbums($idMedium: ID) {
    albums(idMedium: $idMedium) {
        id
        title
        description
        dateCreated
        dateModified
        cover {
            ...FMedia
        }
        owner {
            id
            firstName
            lastName
        },
        albumMedia {
            idMedium
        }
    }
}
