/**
 * @file Automatically generated by barrelsby.
 */

export * from './albums.spec'
export * from './details.spec'
export * from './login.spec'
export * from './media.spec'
export * from './search.spec'
export * from './trash.spec'
export * from './upload.spec'
