query QMedia($album: String, $status: String, $q: String, $favorites: Boolean, $sort: String) {
    media(album: $album, status: $status, q: $q, favorites: $favorites, sort: $sort) {
        ...FMedia
    }
}
