query QMediaYearCount {
    countMediaByYear {
        years {
            months {
                month
                count
            }
            year
            count
        }
        count
    }
}
