query QMedia($status: String, $sort: String, $album: String, $favorites: Boolean, $q: String) {
    media(status: $status, sort: $sort, album: $album, favorites: $favorites, q: $q) {
        ...FMedia
    }
}
