import '@/styles/index.scss'
import 'tippy.js/themes/light.css'

import tippy, { followCursor } from 'tippy.js'
import tauri from '@/tauri'
import { DatepickerConfig } from '@/components/shared/DatepickerConfig'
import { ReactNode } from 'react'
import { BaseProviders } from '@/BaseProviders'
import AuthGuard from '@/api/AuthGuard'

tippy.setDefaultProps({
    zIndex: 101,
    plugins: [followCursor]
})

tauri.createBaseDir()

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
}

export default function RootLayout ({ children }: {
    children: ReactNode
}) {
    return <>
        <DatepickerConfig />
        <html lang="en">
            <body>

                <div
                    id="root"
                >
                    <BaseProviders>
                        <div id="modal-root"></div>
                        {/*<VerifyAccountMessage />*/}
                        <div
                            id="app-root"
                            data-testid="content-root"
                            className="root"
                        >

                            <AuthGuard>
                                {children}
                            </AuthGuard>
                        </div>
                    </BaseProviders>
                </div>
            </body>
        </html>
    </>
}

