mutation MChangePassword($currentPassword: String!, $newPassword: String!, $email: String!) {
    changePassword(currentPassword: $currentPassword, newPassword: $newPassword, email: $email) {
        id
    }
}
