mutation MSignIn (
    $mail: String!
    $password: String!
) {
    signIn(mail: $mail, password: $password) {
        accessToken
        refreshToken
        user {
            ...FUser
        }
    }
}
