mutation MSignUp (
    $mail: String!
    $password: String!
    $firstName: String!
    $lastName: String!
) {
    signUp(
        mail: $mail
        password: $password
        firstName: $firstName
        lastName: $lastName
        language: "en-US"
    ) {
        accessToken
        refreshToken
        user {
            ...FUser
        }
    }
}
