query QAlbums {
    albums {
        id
        title
        description
        dateCreated
        dateModified
        cover {
            ...FCover
        }
        owner {
            id
            firstName
            lastName
        },
        media {
            ...FFlatMedia
        }
    }
}
