query QAlbum($id: String!) {
    album(id: $id) {
        id
        title
        description
        dateCreated
        dateModified
        cover {
            ...FCover
        }
        owner {
            id
            firstName
            lastName
        }
        media {
            ...FMedia
        }
    }
}
