query QAlbums {
    albums {
        id
        title
        description
        dateCreated
        dateModified
        cover {
            id
            mimetype
            filenameDisk
            meta {
                ...on ImageMeta {
                    width
                    height
                }
                ...on VideoMeta {
                    width
                    height
                }
            }
        }
        owner {
            id
            firstName
            lastName
        },
        media {
            ...FMedia
        }
    }
}
