query QAlbums {
    albums {
        id
        title
        description
        dateCreated
        dateModified
        cover {
            id
        }
        owner {
            id
            firstName
            lastName
        },
        media {
            ...FMedia
        }
    }
}
