query QAlbumsOfMedium($id: String!) {
    mediumAlbums(id: $id) {
        id
        title
        dateCreated
        cover {
            ...FCover
        }
        media {
            id
        }
    }
}
