query QAlbumsOfMedium($id: String!) {
    mediumAlbums(id: $id) {
        id
        title
        description
        dateCreated
        dateModified
        cover {
            id
            filenameDisk
        }
        owner {
            id
            firstName
            lastName
        },
        media {
            id
        }
    }
}
