name: Tests

on: [push]

env:
    NODE_ENV: test

jobs:
    tests-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup DB
              run: docker-compose up -d db
            - name: Setup Search
              run: docker-compose up -d search
            - name: Setup Yarn
              uses: actions/setup-node@v3
              with:
                  node-version: 18.12.1
                  cache: 'yarn'
            - name: Install dependencies
              run: yarn install --frozen-lockfile --immutable
            - name: Build Servers
              run: yarn build
              env:
                  NODE_ENV: test
            - name: Tests
              run: yarn test
              env:
                  NODE_ENV: test
