name: Cypress Tests

on: [push]

jobs:
    cypress-run:
        services:
            postgres:
                image: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                  - 5432:5432
                env:
                    POSTGRES_DB: photos
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_USER: stefanbaumeler
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Yarn
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'
            - name: Install dependencies
              run: yarn install --frozen-lockfile --immutable
            - name: Setup DB
              run: NODE_ENV=test yarn db:up
            - name: Seed DB
              run: NODE_ENV=test yarn db:seed
              env:
                  POSTGRES_DB: cy-photos
                  POSTGRES_PASSWORD: postgres
                  POSTGRES_USER: stefanbaumeler
                  PG_DATABASE_NAME: cy-photos
                  PG_DATABASE_USER: stefanbaumeler
                  PG_DATABASE_URI: 127.0.0.1
                  PG_DATABASE_PORT: 5432
                  PG_DATABASE_PASSWORD: postgres
            - name: Check DB
              run: psql cy-photos -l
            - name: Cypress Tests
              uses: cypress-io/github-action@v4.2.0
              with:
                  start: NODE_ENV=test yarn start
                  cy: NODE_ENV=test yarn cy
